version: '3.1'

services:

  persistent-flask:
    container_name: persistent_flask_service
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - DATABASE_URI=mysql+mysqlconnector://root:root@msvc-db:3306/msvc
      - CHOKIDAR_USEPOLLING=true
      - FLASK_DEBUG=1
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_APP=app
    depends_on:
      - msvc-db

  msvc-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: msvc
      MYSQL_USER: user
      MYSQL_PASSWORD: u_pwd
      MYSQL_ROOT_PASSWORD: root
    container_name: msvc-db
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
