version: '3.9'

name: blueprint-flask-test

services:

  msvc-bp-test-api:
    build:
      context: .
      dockerfile: 'Dockerfile.test'
    container_name: msvc-bp-test-api
    environment:
      SECRET_KEY: 'very_secret'