# Docker-Compose Konfiguration für Testumgebung:
# Definiert den Service für die Flask API mit Test-Dockerfile und Umgebungsvariablenname: blueprint-flask-test

services:

  msvc-bp-test-api:
    build:
      context: .
      dockerfile: 'Dockerfile.test'
    container_name: msvc-bp-test-api
    environment:
      SECRET_KEY: 'very_secret'
